### ISSUE TITLE
Clamp images

### ISSUE THREAD

**Issue by vinavfx** [vinavfx/ComfyUI-for-Nuke#11]
While EXR is useful for color bits, it doesn't work for pixel values ​​greater than 1 and less than 0, as it clamping the values. I can't find a solution in ComfyUI. If anyone knows something, I'd appreciate it.

**Comment by vinavfx** [comment]
I'm not even trying to use a model, just an input image with a color node in ComfyUI, I increase the gain and the export is all clamped, it's a ComfyUI problem.

**Comment by avillabon** [comment]
Oh I see. Maybe because the people behind comfyui know the limit is 8bit, it just doesnt allow outputting higher? Just a guess of course. I'd be curious to know as well.

**Comment by vinavfx** [comment]
We will have to wait, so as not to have to juggle everything to fit it into a range between 0 and 1.

**Comment by spacepxl** [comment]
There's no actual reason to limit output images to uint8, because almost every ML model is actually upcasting to fp16 or fp32 internally, even with most quantized models. To get the best possible bit depth, you should use fp32 VAE, but you won't get values outside the 0-1 range because that's not what the models were trained to generate. You could in theory train a model to generate outside that range, but IMO it's easier to compress your values into that range instead using a log colorspace or similar, because that doesn't require retraining.

**Comment by vinavfx** [comment]
The problem is mine, now I have to fix it, thanks for the help.

**Comment by vinavfx** [comment]
solved, thanks avillabon and spacepxl for the boost.
https://github.com/vinavfx/ComfyUI-for-Nuke/commit/709797eedb4e3f84ce83057fe92c0bef40831a23
