### ISSUE TITLE
importer customized knob/widget load

### ISSUE THREAD

**Issue by yuricarrara** [vinavfx/ComfyUI-for-Nuke#15]
I've noticed that if a node knob is customized or dynamic knobs are created (widgets in comfy syntax), the importer doesn't catch those changes because it parses the knobs from the previously generated dict from "update All" button.

Is there a reason why we should not look into the dict from the workflow we are importing and parse from there? This way we should be able to catch all the knobs/widgets customizations.

https://github.com/vinavfx/ComfyUI-for-Nuke/blob/5c75db0e1f92316f3037c0c1b6f21b0cc74f63b0/src/update_menu.py#L30

**Comment by vinavfx** [comment]
You are right about that, the node is created by default as it would be created at the start and does not recognize the modifications of the node of a workflow, I did it that way for the moment because it was the fastest way, I have to think better about how to make it dynamic. This issue will remain open here until someone proposes it or when I have time I look into it.

**Comment by vinavfx** [comment]
All your code works perfectly but
I didn't want to make things more complex, watching Alex Villabon's video, he made me see that the value of the primitive remains in the destination node so I disabled it. The rest of the nodes that are connected as custom, simply do not connect.

I added the groups, getNode and setNode.

When merging your repo I did a revert and left your fork a bit messy, but it remained intact in the yuri_dev branch.

Thanks for the help.

https://github.com/vinavfx/ComfyUI-for-Nuke/commit/47289b3277a1f8f00f800fd2dc8a4c162200a1a8
https://github.com/vinavfx/ComfyUI-for-Nuke/commit/2f85cf8cf13f2fc863b0b1d96892d6323efdbcc6
