### ISSUE TITLE
'utf-32-be' codec can't decode bytes

### ISSUE THREAD

**Issue by screameight** [vinavfx/ComfyUI-for-Nuke#4]
During the submit process, I have the following issue about the websocket : 

"ERROR:websocket:error from callback <function progress.<locals>.on_message at 0x000002B5677BEF80>:
'utf-32-be' codec can't decode bytes in position 8-11: code point not in range(0x110000)"

What does that mean ?

**Comment by vinavfx** [comment]
Does ComfyUi work for you on the web?

**Comment by screameight** [comment]
Yes perfectly

**Comment by vinavfx** [comment]
Can you give me that nuke info:

import websocket
print(sys.version)
print(nuke.NUKE_VERSION_STRING)
print(websocket.__version__)

is it windows?
What comfyui commit are you using?

I need that information to be able to duplicate the error since it works well for me. thank you

**Comment by vinavfx** [comment]
cd ComfyUI
git log

The first one at the top is the commit you should be using

**Comment by screameight** [comment]
I think it’s that : 
commit 6c6a39251fe313c56a88c90d820009073b623dfe
(HEAd ->
master, origin/master)
Author: comfyanonymous
Date:
Tue Apr 2 11:46:34 2024 -0400

thank you !

**Comment by vinavfx** [comment]
Thanks, when I try it I'll tell you

**Comment by Zemram** [comment]
Try using a 'VAEDecode' for XL models, not sdVaeEncode.

**Comment by vinavfx** [comment]
https://github.com/vinavfx/ComfyUI-for-Nuke/pull/24

**Comment by vinavfx** [comment]
@claussteinmassl already fixed this problem, but investigating I saw that in previous versions of Nuke only bytes arrive in the websocket message so returning it by data type does not work, the only solution I found for greater compatibility is to just use try, except so that it does not throw this error, I ask you to support me by testing it to close this unless you have another solution. @screameight 

https://github.com/vinavfx/ComfyUI-for-Nuke/commit/b50ee16809a6cfaf11889476759c4f2af2c4eeac
